version: '2'
services:
  #data container
  data:
    image: debian:jessie
    volumes:
      - ../backend:/var/www/leagueplay

  #mongodb container
  mongodb:
    build: mongodb
    volumes:
      - ../mongo:/data/db
    ports:
      - "27017"

  #webserver container
  node:
    build: node
    volumes_from:
      - data:rw
    ports:
      - "3000"

  # Nginx Web Proxy.
  nginx:
    build:
        context: ./nginx
    depends_on:
      - data
    volumes_from:
      - data:ro
    ports:
      - "80:80"
