version: '2'
services:
  #data container
  data:
    image: debian:jessie

  #mongodb container
  mongodb:
    build: mongodb
    volumes:
      - ../mongo:/data/db
    ports:
      - "27017"

  # Nginx Web Proxy.
  nginx:
    build:
        context: ./nginx
    depends_on:
      - data
    volumes_from:
      - data:ro
    ports:
      - "80:80"
